name: Flutter

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - name: Analyze project
        run: flutter analyze --no-fatal-warnings
